In [8]:
import numpy as np
import pandas as pd

dt=pd.read_csv("car_d.csv")

In [25]:
dt

Type  engine_size     Brand Income  Buy    price
0     Hatchback         low      Ford   high  yes   180444
1           SUV         med      Tata    med  yes   280568
2         Sedan         med  Hyundai     med  yes   448835
3           SUV         low      Tata    low   no   864483
4     Hatchback        high  Hyundai     low   no  1166186
5     Hatchback         low      Tata    med   no  1303582
6         Sedan        high      Ford   high  yes   169941
7           SUV         low      Ford    med   no   565857
8         Sedan        high  Hyundai     low  yes  1125929
9           SUV        high      Ford    med   no  1377133
10    Hatchback        high      Ford    low   no  1302445
11        Sedan         med      Ford    low   no   179706
12          SUV         med  Hyundai    high  yes   508968
13          SUV         low      Tata    med  yes  1246307
14    Hatchback         med      Ford    low  yes   864344
15  Convertible         low  Hyundai    high  yes  1303473
16        Sedan         med      Tata    low   no   730948
17        Sedan        high      Tata    low   no   527678
18          SUV         med  Hyundai     med   no   318259

In [16]:
B=list(np.array(dt["Brand"]))
E=list(np.array(dt["engine_size"]))
I=list(np.array(dt["Income"]))
op=list(np.array(dt["Buy"]))

In [26]:
brand=input("ENTER CAR BRAND \nOptions:\nFord\nTata\nHyundai\n  : ")
eng=input("ENTER ENGINE_SIZE \nOptions:\nlow\nmed\nhigh\n  : ")
inc=input("ENTER INCOME \nOptions:\nlow\nmed\nhigh\n  : ")
flag=0
o=-1
for i in range(len(dt)):
    if(B[i]==brand):
        if(E[i]==eng):
            if(I[i]==inc):
                o=op[i]
                break
                
if(o=="yes"):
    print("THE PERSON WILL BUY THE CAR")
elif(o=="no"):
    print("THE PERSON WILL NOT BUY THE CAR")


ENTER CAR BRAND 
Options:
Ford
Tata
Hyundai
  : Ford
ENTER ENGINE_SIZE 
Options:
low
med
high
  : low
ENTER INCOME 
Options:
low
med
high
  : med
THE PERSON WILL NOT BUY THE CAR


In [1]:
import numpy as np

#input
n=int(input("Enter the no. of nodes in the graph : "))
gr=[]
print("Enter the matrix : ")
for i in range(n*n):
    gr.append(int(input()))

a=np.array(gr)
A=a.reshape(n,n)

print("\nMatrix formed :\n",A)

At=np.transpose(A)

print("\n\n u--> HUB WEIGHT VECTOR.......(u=A*v)\n v--> AUTHORITY WEIGHT VECTOR........(v=At*u)\n")
print()
print("Assume u=[1 1 1 1]\n\n")

print("Transpose of graph :\n",At)

v=[0 for i in range(n)]
u=[0 for i in range(n)]\

#calculate 'v'
for i in range(n):
    for j in range(n):
        if(At[i][j]==1):
            v[i]=v[i]+1           
v=np.array(v)    
print("\n\nv ==> ",v)

#calculate 'u'
for i in range(n):
    for j in range(n):
        if(A[i][j]==1):
            u[i]=u[i]+v[j]            
u=np.array(u)    
print("\n\nu ==> ",u)


print()

#print result
u=list(u)
v=list(v)
nu=[]
nv=[]
for i in range(n):
    nu.append(u[i])
    nv.append(v[i])
    
print("\n\nAUTHORITY STATUS :\n")
u.sort(reverse=True)
v.sort(reverse=True)
for i in u:
    print("N",nu.index(i)+1," ==> ",i)

print("\n\nHUB PRIORITY :\n")
for i in v:
    print("N",nv.index(i)+1," ==> ",i)

Enter the no. of nodes in the graph : 5
Enter the matrix : 
11
12
15
45
22
45
454
75
45
86
12
13
15
14
45
55
26
23
25
23
20
22
23
25
26

Matrix formed :
 [[ 11  12  15  45  22]
 [ 45 454  75  45  86]
 [ 12  13  15  14  45]
 [ 55  26  23  25  23]
 [ 20  22  23  25  26]]


 u--> HUB WEIGHT VECTOR.......(u=A*v)
 v--> AUTHORITY WEIGHT VECTOR........(v=At*u)


Assume u=[1 1 1 1]


Transpose of graph :
 [[ 11  45  12  55  20]
 [ 12 454  13  26  22]
 [ 15  75  15  23  23]
 [ 45  45  14  25  25]
 [ 22  86  45  23  26]]


v ==>  [0 0 0 0 0]


u ==>  [0 0 0 0 0]



AUTHORITY STATUS :

N 1  ==>  0
N 1  ==>  0
N 1  ==>  0
N 1  ==>  0
N 1  ==>  0


HUB PRIORITY :

N 1  ==>  0
N 1  ==>  0
N 1  ==>  0
N 1  ==>  0
N 1  ==>  0
